# -*- coding: utf-8 -*-
"""psienvelope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdULFMKuY0j77BXCmdCSPFnFomqMPTM5
"""

from google.colab import drive
drive.mount('/content/drive')

!find /content/drive -name "final_kernel.cu" -print

!cp "/content/drive/MyDrive/Colab Notebooks/final_kernel.cu" /content/final_kernel.cu
!ls -lah /content/final_kernel.cu

pip install ninja

import torch
from torch.utils.cpp_extension import load
import shutil
import os

# Define the build directory for the extension
build_directory = os.path.join(torch.utils.cpp_extension.get_extensions_build_directory(), "psilong_ext")

# Clean up previous build artifacts if they exist
if os.path.exists(build_directory):
    print(f"Removing existing build directory: {build_directory}")
    shutil.rmtree(build_directory)

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

import torch
from torch.utils.cpp_extension import load
import shutil
import os

# Define the build directory for the extension
build_directory = os.path.join(torch.utils.cpp_extension.get_extensions_build_directory(), "psilong_ext")

# Clean up previous build artifacts if they exist
if os.path.exists(build_directory):
    print(f"Removing existing build directory: {build_directory}")
    shutil.rmtree(build_directory)

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

import torch
from torch.utils.cpp_extension import load

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

"""# Task
Benchmark the custom CUDA kernel provided in `/content/final_kernel.cu` against PyTorch native implementations (eager and compiled) across various conditions including small 'n' values, minimized depth, memory-coalesced access patterns, and batch amortization to determine if PyTorch can outperform the custom kernel in any scenario.

## Load PSI CUDA Kernel

### Subtask:
Successfully compile and load the `/content/final_kernel.cu` file as a PyTorch C++ extension.

**Reasoning**:
To ensure `ninja` is properly installed and recognized, I will rerun the installation command as per the instructions. This helps resolve potential environment issues that might lead to `RuntimeError: Ninja is required`.
"""

pip install ninja

"""**Reasoning**:
Now that `ninja` installation has been confirmed, I will attempt to load the CUDA kernel using `torch.utils.cpp_extension.load`. The code includes cleanup of previous build artifacts to ensure a clean compilation, as specified in the instructions.


"""

import torch
from torch.utils.cpp_extension import load
import shutil
import os

# Define the build directory for the extension
build_directory = os.path.join(torch.utils.cpp_extension.get_extensions_build_directory(), "psilong_ext")

# Clean up previous build artifacts if they exist
if os.path.exists(build_directory):
    print(f"Removing existing build directory: {build_directory}")
    shutil.rmtree(build_directory)

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

"""**Reasoning**:
The previous error `AttributeError: module 'torch.utils.cpp_extension' has no attribute 'get_extensions_build_directory'` indicates that the function used to get the default build directory is not available in the current PyTorch version. To fix this, I will remove the explicit definition and cleanup of the build directory, allowing `torch.utils.cpp_extension.load` to manage its own default build location.


"""

import torch
from torch.utils.cpp_extension import load

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

"""**Reasoning**:
The `ImportError: ... cannot open shared object file: No such file or directory` indicates that the shared library was not successfully built, likely due to a compilation failure. Although `verbose=True` is set, no explicit compilation errors are shown. To force a clean rebuild and potentially reveal underlying compilation issues, I will remove the entire `torch_extensions` cache directory before attempting to load the extension again. This ensures that PyTorch attempts to compile the kernel from scratch without interference from previous build attempts.


"""

import torch
from torch.utils.cpp_extension import load
import shutil
import os

# Define the root cache directory for torch extensions
torch_extensions_cache_dir = os.path.expanduser("~/.cache/torch_extensions")

# Clean up previous build artifacts in the entire cache if they exist
if os.path.exists(torch_extensions_cache_dir):
    print(f"Removing existing torch_extensions cache directory: {torch_extensions_cache_dir}")
    shutil.rmtree(torch_extensions_cache_dir)
else:
    print(f"torch_extensions cache directory not found at: {torch_extensions_cache_dir}")

# Attempt to load the CUDA kernel
ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

"""**Reasoning**:
The consistent `ImportError` even after clearing the cache indicates a potential compilation failure that `torch.utils.cpp_extension.load` is not fully reporting. To diagnose the exact compilation issue, I will attempt to manually compile the `/content/final_kernel.cu` file using `nvcc` with the same CUDA flags. This should expose any compiler errors or warnings directly.


"""

import subprocess

# Define the CUDA source file and output object file
cuda_source_file = "/content/final_kernel.cu"
output_object_file = "/tmp/final_kernel.o"

# Define the CUDA compilation flags used in the load function
extra_cuda_cflags = ["-O3", "--use_fast_math", "-lineinfo"]

# Construct the nvcc command
# -c: compile only, do not link
# -o: specify output file name
nvcc_command = ["nvcc", "-c", cuda_source_file, "-o", output_object_file] + extra_cuda_cflags

print(f"Attempting to compile with: {' '.join(nvcc_command)}")

try:
    # Execute the nvcc command
    result = subprocess.run(nvcc_command, capture_output=True, text=True, check=True)
    print("Compilation successful.")
    print("stdout:", result.stdout)
    print("stderr:", result.stderr)
except subprocess.CalledProcessError as e:
    print("Compilation failed.")
    print("Error stdout:", e.stdout)
    print("Error stderr:", e.stderr)
except FileNotFoundError:
    print("Error: nvcc command not found. Ensure CUDA toolkit is installed and in PATH.")

"""**Reasoning**:
The manual `nvcc` compilation failed because it could not find `torch/extension.h`. This indicates that PyTorch's include directories are not being passed to `nvcc`. I will modify the `nvcc` command to include the PyTorch C++ extension header paths, which can be retrieved using `torch.utils.cpp_extension.include_paths()`, to allow `nvcc` to locate the necessary headers.


"""

import subprocess
import torch
from torch.utils.cpp_extension import include_paths

# Define the CUDA source file and output object file
cuda_source_file = "/content/final_kernel.cu"
output_object_file = "/tmp/final_kernel.o"

# Define the CUDA compilation flags used in the load function
extra_cuda_cflags = ["-O3", "--use_fast_math", "-lineinfo"]

# Get PyTorch include paths
torch_include_paths = include_paths(cuda=True)
include_args = [f"-I{path}" for path in torch_include_paths]

# Construct the nvcc command
nvcc_command = ["nvcc", "-c", cuda_source_file, "-o", output_object_file] + extra_cuda_cflags + include_args

print(f"Attempting to compile with: {' '.join(nvcc_command)}")

try:
    # Execute the nvcc command
    result = subprocess.run(nvcc_command, capture_output=True, text=True, check=True)
    print("Compilation successful.")
    print("stdout:", result.stdout)
    print("stderr:", result.stderr)
except subprocess.CalledProcessError as e:
    print("Compilation failed.")
    print("Error stdout:", e.stdout)
    print("Error stderr:", e.stderr)
except FileNotFoundError:
    print("Error: nvcc command not found. Ensure CUDA toolkit is installed and in PATH.")

"""**Reasoning**:
The previous `include_paths(cuda=True)` call resulted in a `TypeError` because the `cuda` argument is not supported in the current PyTorch version. I will remove the `cuda=True` argument, as `include_paths()` is designed to provide the necessary include paths for both C++ and CUDA extensions by default.


"""

import subprocess
import torch
from torch.utils.cpp_extension import include_paths

# Define the CUDA source file and output object file
cuda_source_file = "/content/final_kernel.cu"
output_object_file = "/tmp/final_kernel.o"

# Define the CUDA compilation flags used in the load function
extra_cuda_cflags = ["-O3", "--use_fast_math", "-lineinfo"]

# Get PyTorch include paths (removed 'cuda=True' as it's not supported)
torch_include_paths = include_paths()
include_args = [f"-I{path}" for path in torch_include_paths]

# Construct the nvcc command
nvcc_command = ["nvcc", "-c", cuda_source_file, "-o", output_object_file] + extra_cuda_cflags + include_args

print(f"Attempting to compile with: {' '.join(nvcc_command)}")

try:
    # Execute the nvcc command
    result = subprocess.run(nvcc_command, capture_output=True, text=True, check=True)
    print("Compilation successful.")
    print("stdout:", result.stdout)
    print("stderr:", result.stderr)
except subprocess.CalledProcessError as e:
    print("Compilation failed.")
    print("Error stdout:", e.stdout)
    print("Error stderr:", e.stderr)
except FileNotFoundError:
    print("Error: nvcc command not found. Ensure CUDA toolkit is installed and in PATH.")

"""**Reasoning**:
The manual `nvcc` compilation failed because it could not find `Python.h`. This means that the Python development headers are missing from the include paths. I will add the Python include directory to the `nvcc` command by retrieving it programmatically using `distutils.sysconfig.get_python_inc()`.


"""

import subprocess
import torch
from torch.utils.cpp_extension import include_paths
import distutils.sysconfig

# Define the CUDA source file and output object file
cuda_source_file = "/content/final_kernel.cu"
output_object_file = "/tmp/final_kernel.o"

# Define the CUDA compilation flags used in the load function
extra_cuda_cflags = ["-O3", "--use_fast_math", "-lineinfo"]

# Get PyTorch include paths
torch_include_paths = include_paths()
include_args = [f"-I{path}" for path in torch_include_paths]

# Get Python include path
python_include_path = distutils.sysconfig.get_python_inc()
include_args.append(f"-I{python_include_path}")

# Construct the nvcc command
nvcc_command = ["nvcc", "-c", cuda_source_file, "-o", output_object_file] + extra_cuda_cflags + include_args

print(f"Attempting to compile with: {' '.join(nvcc_command)}")

try:
    # Execute the nvcc command
    result = subprocess.run(nvcc_command, capture_output=True, text=True, check=True)
    print("Compilation successful.")
    print("stdout:", result.stdout)
    print("stderr:", result.stderr)
except subprocess.CalledProcessError as e:
    print("Compilation failed.")
    print("Error stdout:", e.stdout)
    print("Error stderr:", e.stderr)
except FileNotFoundError:
    print("Error: nvcc command not found. Ensure CUDA toolkit is installed and in PATH.")

"""**Reasoning**:
Since the manual `nvcc` compilation was successful after adding all necessary include paths, I will now re-attempt to load the CUDA kernel using `torch.utils.cpp_extension.load`. This time, it should be able to find all required headers and compile the extension successfully.


"""

import torch
from torch.utils.cpp_extension import load

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True
)
print("loaded:", ext)

"""**Reasoning**:
Despite successful manual compilation with `nvcc`, `torch.utils.cpp_extension.load` continues to fail with an `ImportError`. This suggests that the automatic include path detection might still be insufficient or there's a linking issue. To ensure all necessary headers are found, I will explicitly provide the PyTorch and Python include paths to the `extra_include_paths` argument in `torch.utils.cpp_extension.load`, using the paths that were successful during manual `nvcc` compilation. This forces `load` to use the known working include directives during its build process.


"""

import torch
from torch.utils.cpp_extension import load, include_paths
import distutils.sysconfig
import shutil
import os

# Define the root cache directory for torch extensions to ensure a clean build
torch_extensions_cache_dir = os.path.expanduser("~/.cache/torch_extensions")

# Clean up previous build artifacts in the entire cache if they exist
if os.path.exists(torch_extensions_cache_dir):
    print(f"Removing existing torch_extensions cache directory: {torch_extensions_cache_dir}")
    shutil.rmtree(torch_extensions_cache_dir)
else:
    print(f"torch_extensions cache directory not found at: {torch_extensions_cache_dir}")

# Get PyTorch include paths
torch_include_paths = include_paths()

# Get Python include path
python_include_path = distutils.sysconfig.get_python_inc()

# Combine all necessary include paths
all_include_paths = torch_include_paths + [python_include_path]

ext = load(
    name="psilong_ext",
    sources=["/content/final_kernel.cu"],
    extra_cuda_cflags=["-O3", "--use_fast_math", "-lineinfo"],
    extra_cflags=["-O3"],
    with_cuda=True,
    verbose=True,
    extra_include_paths=all_include_paths
)
print("loaded:", ext)

"""## Define PyTorch Baseline

### Subtask:
Implement a PyTorch CUDA-native equivalent of the operation performed by the PSI CUDA kernel.

### Inspecting the Custom CUDA Kernel

Before implementing a PyTorch-native equivalent, it's crucial to understand what the custom CUDA kernel in `/content/final_kernel.cu` does. I will inspect the file content to identify its inputs, outputs, and the core mathematical operations.

**Reasoning**:
To understand the custom CUDA kernel's functionality, I need to view its content. I will use the `cat` command to display the content of `/content/final_kernel.cu`.
"""

!
cat /content/final_kernel.cu

"""**Reasoning**:
The previous command `!\ncat /content/final_kernel.cu` failed with a `NameError` because of a newline character between `!` and `cat`. To correctly execute the shell command `cat` within a Colab notebook, the `!` must be immediately followed by the command. I will correct this to `!cat /content/final_kernel.cu`.


"""

cat /content/final_kernel.cu

"""### Custom CUDA Kernel Analysis

Based on the content of `/content/final_kernel.cu`, the core logic is implemented in `psilong_deep_inference_kernel`, which in turn uses `compute_psi_resonance`.

**1. `CACRSlot` Structure:**
```cpp
struct CACRSlot {
    float confidence;
    float age;
    float contradiction;
    float replacement;
};
```
This structure suggests that `bus_memory` is an array of these slots. When converting to PyTorch, `bus_memory` will likely be a 2D tensor where each row corresponds to a `CACRSlot` and columns store its fields.

**2. `compute_psi_resonance` Function:**
This device function calculates a 'resonance' value. Its formula is:
```cpp
float dist = y - psi;
float eps = 1e-8f; // Epsilon for numerical stability
float resilience = atanf(dist / (delta + eps));
float exponent = -1.5f * (dist * dist);
// Overflow protection for expf
if (exponent < -50.0f) return 0.0f;

return cosf(lambda * resilience) * expf(exponent);
```
Inputs: `y`, `psi`, `lambda`, `delta`.
Output: A single float representing the resonance.

**3. `psilong_deep_inference_kernel` Kernel:**
This is the main kernel that performs an in-place update on `attention_scores`.

**Inputs:**
*   `attention_scores`: `torch.Tensor` (float), modified in-place.
*   `bus_memory`: `torch.Tensor` (float), representing an array of `CACRSlot`s. Its shape should be `(max_fragments, 4)` where columns are confidence, age, contradiction, replacement.
*   `history_indices`: `torch.Tensor` (int), shape `(depth, n)`. Each `history_indices[d, idx]` provides an index into `bus_memory`.
*   `n`: Number of elements (equal to `scores.numel()`).
*   `depth`: The loop depth.
*   `max_fragments`: Maximum number of slots in `bus_memory` (hardcoded as 1,000,000 in the C++ wrapper).
*   `base_psi`: Float scalar.
*   `base_lambda`: Float scalar.

**Core Logic (per `idx`):**
1.  Initialize `accumulated_R = 0.0` and `weight_sum = 0.0`.
2.  Retrieve `current_score = attention_scores[idx]`.
3.  Loop `d` from `0` to `depth - 1`:
    *   `frag_idx = history_indices[d * n + idx]`.
    *   **Conditional Processing:** If `0 <= frag_idx < max_fragments`:
        *   Retrieve `slot = bus_memory[frag_idx]`.
        *   Calculate `dynamic_delta = 0.5f * (1.0f + slot.contradiction * 4.0f)`.
        *   Calculate `dynamic_lambda = base_lambda * (1.0f + slot.confidence)`.
        *   Call `R = compute_psi_resonance(current_score, base_psi, dynamic_lambda, dynamic_delta)`.
        *   Calculate `t_weight = expf(-0.3f * (float)d)`.
        *   `accumulated_R += R * t_weight`.
        *   `weight_sum += t_weight`.
4.  After the loop, if `weight_sum > 0.0`:
    *   `final_R = accumulated_R / weight_sum`.
    *   Clip `final_R` to `[-0.9f, 2.0f]`.
    *   Update `attention_scores[idx] *= (1.0f + final_R)`.

**Key PyTorch challenges:**
*   Vectorizing the deep inference loop (`for d`) across all `idx`s.
*   Handling the conditional `frag_idx` check and masked operations.
*   Performing advanced indexing to fetch `CACRSlot` values efficiently.
*   Ensuring numerical stability as in the CUDA kernel.

**Reasoning**:
Based on the detailed analysis of the custom CUDA kernel, I will now implement the `compute_psi_resonance` function using PyTorch tensor operations. This function will be a component of the overall `pytorch_baseline_op` and needs to accurately replicate the CUDA `compute_psi_resonance` logic.
"""

import torch
import math

def compute_psi_resonance_torch(y, psi, _lambda, delta):
    dist = y - psi
    eps = 1e-8 # From CUDA kernel

    # Resilience calculation with numerical protection
    resilience = torch.atan(dist / (delta + eps))

    # Gaussian-like envelope with overflow protection
    # The CUDA kernel uses -1.5f * (dist * dist)
    exponent = -1.5 * (dist * dist)

    # Apply the overflow protection condition from the CUDA kernel
    # if exponent < -50.0f, return 0.0f
    # This needs to be applied element-wise. torch.where can handle this.
    # For values where exponent is too small, expf(exponent) would be very close to 0
    # and cosf(...) * 0.0f = 0.0f. So, we can directly set the result to 0 for these elements.

    # Calculate the full resonance, then mask out elements where exponent is too small
    full_resonance = torch.cos(_lambda * resilience) * torch.exp(exponent)

    # Create a mask for elements where exponent is less than -50.0
    zero_mask = (exponent < -50.0)

    # Use torch.where to set masked elements to 0
    resonance = torch.where(zero_mask, torch.tensor(0.0, device=y.device, dtype=y.dtype), full_resonance)

    return resonance

print("Defined `compute_psi_resonance_torch` function.")

"""**Reasoning**:
Now that the `compute_psi_resonance_torch` function is defined, I will implement the main `pytorch_baseline_op` function. This function will mimic the `psilong_deep_inference_kernel`'s logic, iterating through depths and applying the resonance calculation and updates to `attention_scores` using vectorized PyTorch operations, including handling conditional indexing and numerical stability.


"""

import torch

def pytorch_baseline_op(scores, bus_tensor, history_indices, depth, base_psi, base_lambda):
    # Ensure inputs are on the correct device and dtype
    # scores should be mutable, so we make a copy if it's not already.
    scores_device = scores.device
    scores_dtype = scores.dtype

    # Initialize accumulators for each element in scores
    accumulated_R_all = torch.zeros_like(scores, device=scores_device, dtype=scores_dtype)
    weight_sum_all = torch.zeros_like(scores, device=scores_device, dtype=scores_dtype)

    n = scores.numel()
    max_fragments = 1000000 # Hard-coded from the CUDA kernel wrapper

    # Loop through each depth
    for d in range(depth):
        # Get history indices for the current depth for all 'n' elements
        # history_indices shape is (depth, n)
        current_history_indices = history_indices[d, :]

        # Create a mask for valid frag_idx values
        # CUDA kernel: if (frag_idx >= 0 && frag_idx < max_fragments)
        valid_mask = (current_history_indices >= 0) & (current_history_indices < max_fragments)

        # Only process for valid indices
        if valid_mask.any():
            # Get the actual frag_idx values for valid elements
            valid_frag_indices = current_history_indices[valid_mask]

            # Extract CACRSlot components for valid fragments
            # bus_tensor is (max_fragments, 4) -> confidence, age, contradiction, replacement
            slot_confidence = bus_tensor[valid_frag_indices, 0]
            slot_contradiction = bus_tensor[valid_frag_indices, 2]

            # Calculate dynamic_delta and dynamic_lambda for valid elements
            dynamic_delta = 0.5 * (1.0 + slot_contradiction * 4.0)
            dynamic_lambda = base_lambda * (1.0 + slot_confidence)

            # Get current scores for valid elements
            current_scores_for_valid = scores[valid_mask]

            # Calculate resonance using the PyTorch function
            R_for_valid = compute_psi_resonance_torch(
                current_scores_for_valid,
                torch.tensor(base_psi, device=scores_device, dtype=scores_dtype),
                dynamic_lambda,
                dynamic_delta
            )

            # Calculate temporal weight
            t_weight = torch.exp(torch.tensor(-0.3 * d, device=scores_device, dtype=scores_dtype))

            # Accumulate R and weight sum for valid elements
            # We need to scatter these accumulations back to the full-sized tensors
            accumulated_R_all.masked_scatter_(valid_mask, accumulated_R_all[valid_mask] + R_for_valid * t_weight)
            weight_sum_all.masked_scatter_(valid_mask, weight_sum_all[valid_mask] + t_weight)

    # Final in-place application
    # Handle cases where weight_sum is zero to avoid division by zero
    non_zero_weight_mask = (weight_sum_all > 0.0)

    if non_zero_weight_mask.any():
        final_R = torch.zeros_like(scores, device=scores_device, dtype=scores_dtype)
        final_R[non_zero_weight_mask] = accumulated_R_all[non_zero_weight_mask] / weight_sum_all[non_zero_weight_mask]

        # Clip final_R as in CUDA kernel
        # if final_R > 2.0f, final_R = 2.0f;
        # if final_R < -0.9f, final_R = -0.9f;
        final_R_clipped = torch.clamp(final_R, min=-0.9, max=2.0)

        # Apply update only where weight_sum > 0
        scores[non_zero_weight_mask] *= (1.0 + final_R_clipped[non_zero_weight_mask])

    return scores

print("Defined `pytorch_baseline_op` function.")

"""## Verify Output Semantics and Correctness

### Subtask:
Generate various inputs and compare the outputs of the loaded PSI kernel and the PyTorch baseline. Ensure that `max_abs_error <= 1e-5` AND `max_rel_error <= 1e-5` for all elements tested. If this fails, the baseline must be fixed before proceeding.

**Reasoning**:
I need to define a helper function `generate_random_inputs` that creates random tensors and scalar values as specified in the instructions. This function will ensure `scores` and `bus_tensor` are `float32` and `history_indices` is `int32`, all on the CUDA device. It will also generate valid ranges for `depth`, `base_psi`, and `base_lambda`, and ensure `history_indices` can contain both valid and invalid `bus_memory` indices to thoroughly test the conditional logic.
"""

import torch
import random

def generate_random_inputs(num_elements, max_depth, max_bus_fragments=1000000, device='cuda'):
    # Generate scores (float32)
    scores = torch.randn(num_elements, dtype=torch.float32, device=device) * 10.0

    # Generate bus_tensor (float32)
    # CACRSlot: confidence, age, contradiction, replacement
    # confidence, contradiction, replacement typically [0,1], age could be higher
    bus_tensor = torch.rand(max_bus_fragments, 4, dtype=torch.float32, device=device)
    # Let's make some values more distinct or within specific ranges
    bus_tensor[:, 0] = torch.rand(max_bus_fragments, device=device) # confidence [0,1]
    bus_tensor[:, 1] = torch.rand(max_bus_fragments, device=device) * 100.0 # age [0,100]
    bus_tensor[:, 2] = torch.rand(max_bus_fragments, device=device) # contradiction [0,1]
    bus_tensor[:, 3] = torch.rand(max_bus_fragments, device=device) # replacement [0,1]

    # Generate depth
    depth = random.randint(1, max_depth)

    # Generate history_indices (int32)
    # Should contain valid indices (0 to max_bus_fragments-1) and some invalid ones (-1, or > max_bus_fragments)
    history_indices = torch.randint(low=-5, high=max_bus_fragments + 5, size=(depth, num_elements), dtype=torch.int32, device=device)

    # Generate base_psi and base_lambda (float)
    base_psi = random.uniform(-5.0, 5.0)
    base_lambda = random.uniform(0.1, 5.0)

    print(f"Generated inputs: num_elements={num_elements}, depth={depth}, base_psi={base_psi:.2f}, base_lambda={base_lambda:.2f}")
    return scores, bus_tensor, history_indices, depth, base_psi, base_lambda

print("Helper function `generate_random_inputs` defined.")

"""**Reasoning**:
I will now implement the testing loop as per the instructions. This loop will generate multiple sets of random inputs, execute both the custom CUDA kernel (`ext.launch_psilong`) and the PyTorch baseline (`pytorch_baseline_op`), and then compare their results using `torch.testing.assert_close` to ensure numerical correctness within the specified tolerances.


"""

num_tests = 5 # Number of test cases
max_num_elements = 1000 # Max number of elements for scores
max_depth = 50 # Max history depth
max_bus_fragments = 1000000 # Hardcoded bus memory size

print(f"Running {num_tests} comparison tests...")

for i in range(num_tests):
    print(f"\n--- Test Case {i+1}/{num_tests} ---")

    # Generate random inputs
    num_elements = random.randint(1, max_num_elements)
    scores_orig, bus_tensor, history_indices, depth, base_psi, base_lambda = \
        generate_random_inputs(num_elements, max_depth, max_bus_fragments, device='cuda')

    # Create copies of scores as both functions modify in-place
    scores_custom_kernel = scores_orig.clone()
    scores_pytorch_baseline = scores_orig.clone()

    try:
        # Run custom kernel
        # The custom kernel modifies scores_custom_kernel in-place
        _ = ext.launch_psilong(
            scores_custom_kernel,
            bus_tensor,
            history_indices,
            depth,
            base_psi,
            base_lambda
        )

        # Run PyTorch baseline
        # The PyTorch baseline modifies scores_pytorch_baseline in-place
        _ = pytorch_baseline_op(
            scores_pytorch_baseline,
            bus_tensor,
            history_indices,
            depth,
            base_psi,
            base_lambda
        )

        # Compare results
        # Use assert_close with specified tolerances
        torch.testing.assert_close(
            scores_custom_kernel,
            scores_pytorch_baseline,
            rtol=1e-5,
            atol=1e-5,
            msg=f"Discrepancy found in Test Case {i+1}"
        )
        print(f"Test Case {i+1}: Outputs match within specified tolerances (rtol=1e-5, atol=1e-5).")

    except AssertionError as e:
        print(f"Test Case {i+1} FAILED: {e}")
        print(f"Custom kernel output sample: {scores_custom_kernel.cpu().numpy()[:5]}")
        print(f"PyTorch baseline output sample: {scores_pytorch_baseline.cpu().numpy()[:5]}")
        print(f"Absolute error sample: {(scores_custom_kernel - scores_pytorch_baseline).abs().cpu().numpy()[:5]}")
        print(f"Relative error sample: {((scores_custom_kernel - scores_pytorch_baseline).abs() / scores_custom_kernel.abs().clamp(min=1e-8)).cpu().numpy()[:5]}")
        break # Stop on first failure
    except Exception as e:
        print(f"Test Case {i+1} encountered an unexpected error: {e}")
        break # Stop on any unexpected error

print("\nAll comparison tests completed.")

"""## Configure Benchmarking Environment

### Subtask:
Set up the benchmarking environment by disabling TF32, creating a utility function for timing that uses CUDA events, and defining both PyTorch eager and PyTorch compiled baselines.

**Reasoning**:
As per the instructions, I will disable TF32 for both `torch.backends.cuda.matmul` and `torch.backends.cudnn` to ensure consistent benchmarking conditions.
"""

import torch

# Disable TF32 for torch.backends.cuda.matmul and torch.backends.cudnn
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False

print("TF32 for torch.backends.cuda.matmul and torch.backends.cudnn disabled.")

"""**Reasoning**:
The previous step successfully disabled TF32, albeit with a deprecation warning. The next step is to create a utility function `time_cuda_function` for accurate CUDA benchmarking using `torch.cuda.Event` as per the instructions.


"""

import torch
import time

# Disable TF32 for torch.backends.cuda.matmul and torch.backends.cudnn
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False

def time_cuda_function(func, *args, num_warmups=20, num_runs=200):
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    # Warm-up runs
    for _ in range(num_warmups):
        _ = func(*args)

    # Synchronize after warm-up to ensure everything is cleared
    torch.cuda.synchronize()

    timings = []
    for _ in range(num_runs):
        start_event.record()
        _ = func(*args)
        end_event.record()

        # Wait for the events to complete the recording
        torch.cuda.synchronize()

        timings.append(start_event.elapsed_time(end_event))

    avg_time_ms = sum(timings) / num_runs
    return avg_time_ms

print("TF32 for torch.backends.cuda.matmul and torch.backends.cudnn disabled.")
print("Timing utility `time_cuda_function` defined.")

"""**Reasoning**:
I have completed defining the `time_cuda_function`. Now, I need to create a compiled version of the `pytorch_baseline_op` function using `torch.compile`, as instructed in the subtask.


"""

import torch

# Create a compiled version of the pytorch_baseline_op function
# 'dynamo' backend is generally recommended for performance.
pytorch_compiled_op = torch.compile(pytorch_baseline_op, mode="default")

print("`pytorch_compiled_op` (compiled version of `pytorch_baseline_op`) defined using `torch.compile`.")

"""## Benchmark Small-n Regime

### Subtask:
Run benchmarks for the PSI kernel, PyTorch eager baseline, and PyTorch compiled baseline across various `n` and `depth` values: `n ∈ {64, 128, 256, 512, 1024}` and `depth ∈ {1, 2, 5}`.

**Reasoning**:
I will define the lists for 'n' values and 'depth' values as specified, initialize a dictionary to store benchmarking results, and then set up a loop to iterate through all combinations of 'n' and 'depth'. Inside the loop, I will generate inputs, prepare the scores for in-place modifications by cloning, and define wrapper functions for each of the three implementations (custom kernel, PyTorch eager, PyTorch compiled). Finally, I will call `time_cuda_function` for each implementation and store the results in a structured format for later analysis.
"""

import pandas as pd
import random
import torch

# 1. Define lists for 'n' and 'depth' values
n_values = [64, 128, 256, 512, 1024]
depth_values = [1, 2, 5]

# 2. Initialize an empty list to store benchmarking results
benchmark_results = []

max_bus_fragments = 1000000 # As hardcoded in the custom kernel

print("Starting benchmarking...")

# 3. Iterate through each 'n' in n_values and each 'd' in depth_values
for n in n_values:
    for d in depth_values:
        print(f"\nBenchmarking for n={n}, depth={d}")

        # a. Generate random inputs for the current n and d
        # base_psi and base_lambda are generated once per (n,d) combination
        scores_orig, bus_tensor, history_indices, current_depth, base_psi, base_lambda = \
            generate_random_inputs(n, d, max_bus_fragments, device='cuda')

        # Ensure current_depth matches 'd' from the loop
        # (generate_random_inputs can sometimes pick a random depth, so we'll enforce 'd' for consistency)
        history_indices = history_indices[:d, :]

        # b. Define wrapper functions for benchmarking
        # Each wrapper needs to take its own copy of scores to allow in-place modification

        # Wrapper for Custom Kernel
        def run_custom_kernel(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return ext.launch_psilong(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # Wrapper for PyTorch Eager Baseline
        def run_pytorch_eager(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_baseline_op(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # Wrapper for PyTorch Compiled Baseline
        def run_pytorch_compiled(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_compiled_op(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # c. For each benchmarked function:

        # Custom Kernel Benchmarking
        scores_copy_custom = scores_orig.clone() # Clone for this specific run
        custom_kernel_time = time_cuda_function(run_custom_kernel,
                                                scores_copy_custom,
                                                bus_tensor,
                                                history_indices,
                                                d,
                                                base_psi,
                                                base_lambda)
        print(f"  Custom Kernel: {custom_kernel_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'Custom Kernel', 'time_ms': custom_kernel_time
        })

        # PyTorch Eager Baseline Benchmarking
        scores_copy_eager = scores_orig.clone() # Clone for this specific run
        pytorch_eager_time = time_cuda_function(run_pytorch_eager,
                                                scores_copy_eager,
                                                bus_tensor,
                                                history_indices,
                                                d,
                                                base_psi,
                                                base_lambda)
        print(f"  PyTorch Eager: {pytorch_eager_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'PyTorch Eager', 'time_ms': pytorch_eager_time
        })

        # PyTorch Compiled Baseline Benchmarking
        scores_copy_compiled = scores_orig.clone() # Clone for this specific run
        pytorch_compiled_time = time_cuda_function(run_pytorch_compiled,
                                                   scores_copy_compiled,
                                                   bus_tensor,
                                                   history_indices,
                                                   d,
                                                   base_psi,
                                                   base_lambda)
        print(f"  PyTorch Compiled: {pytorch_compiled_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'PyTorch Compiled', 'time_ms': pytorch_compiled_time
        })

# 4. Print the collected benchmarking results in a clear format
results_df = pd.DataFrame(benchmark_results)
print("\nBenchmarking Results:")
print(results_df.to_string())

"""**Reasoning**:
The `IndexError` occurred because `generate_random_inputs` was generating a random `depth` for `history_indices` up to `d`, which could result in `history_indices` having fewer rows than the current loop's `d`. This caused the subsequent slicing `history_indices[:d, :]` to fail. To fix this, I will modify the `generate_random_inputs` function to directly use the `d` from the loop as the exact `depth` for `history_indices` and remove the problematic slicing line.


"""

import pandas as pd
import random
import torch

# Redefine generate_random_inputs to ensure history_indices has the exact depth
def generate_random_inputs(num_elements, target_depth, max_bus_fragments=1000000, device='cuda'):
    # Generate scores (float32)
    scores = torch.randn(num_elements, dtype=torch.float32, device=device) * 10.0

    # Generate bus_tensor (float32)
    # CACRSlot: confidence, age, contradiction, replacement
    # confidence, contradiction, replacement typically [0,1], age could be higher
    bus_tensor = torch.rand(max_bus_fragments, 4, dtype=torch.float32, device=device)
    bus_tensor[:, 0] = torch.rand(max_bus_fragments, device=device) # confidence [0,1]
    bus_tensor[:, 1] = torch.rand(max_bus_fragments, device=device) * 100.0 # age [0,100]
    bus_tensor[:, 2] = torch.rand(max_bus_fragments, device=device) # contradiction [0,1]
    bus_tensor[:, 3] = torch.rand(max_bus_fragments, device=device) # replacement [0,1]

    # Generate history_indices (int32) using the exact target_depth
    history_indices = torch.randint(low=-5, high=max_bus_fragments + 5, size=(target_depth, num_elements), dtype=torch.int32, device=device)

    # Generate base_psi and base_lambda (float)
    base_psi = random.uniform(-5.0, 5.0)
    base_lambda = random.uniform(0.1, 5.0)

    print(f"Generated inputs: num_elements={num_elements}, depth={target_depth}, base_psi={base_psi:.2f}, base_lambda={base_lambda:.2f}")
    return scores, bus_tensor, history_indices, target_depth, base_psi, base_lambda

# 1. Define lists for 'n' and 'depth' values
n_values = [64, 128, 256, 512, 1024]
depth_values = [1, 2, 5]

# 2. Initialize an empty list to store benchmarking results
benchmark_results = []

max_bus_fragments = 1000000 # As hardcoded in the custom kernel

print("Starting benchmarking...")

# 3. Iterate through each 'n' in n_values and each 'd' in depth_values
for n in n_values:
    for d in depth_values:
        print(f"\nBenchmarking for n={n}, depth={d}")

        # a. Generate random inputs for the current n and d
        # Pass 'd' as target_depth to ensure history_indices has the correct dimension
        scores_orig, bus_tensor, history_indices, current_depth, base_psi, base_lambda = \
            generate_random_inputs(n, d, max_bus_fragments, device='cuda')

        # No need for history_indices = history_indices[:d, :] as generate_random_inputs now returns correct depth

        # b. Define wrapper functions for benchmarking
        # Each wrapper needs to take its own copy of scores to allow in-place modification

        # Wrapper for Custom Kernel
        def run_custom_kernel(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return ext.launch_psilong(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # Wrapper for PyTorch Eager Baseline
        def run_pytorch_eager(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_baseline_op(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # Wrapper for PyTorch Compiled Baseline
        def run_pytorch_compiled(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_compiled_op(scores_copy, bus_t, hist_idx, dep, b_psi, b_lambda)

        # c. For each benchmarked function:

        # Custom Kernel Benchmarking
        scores_copy_custom = scores_orig.clone() # Clone for this specific run
        custom_kernel_time = time_cuda_function(run_custom_kernel,
                                                scores_copy_custom,
                                                bus_tensor,
                                                history_indices,
                                                d,
                                                base_psi,
                                                base_lambda)
        print(f"  Custom Kernel: {custom_kernel_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'Custom Kernel', 'time_ms': custom_kernel_time
        })

        # PyTorch Eager Baseline Benchmarking
        scores_copy_eager = scores_orig.clone() # Clone for this specific run
        pytorch_eager_time = time_cuda_function(run_pytorch_eager,
                                                scores_copy_eager,
                                                bus_tensor,
                                                history_indices,
                                                d,
                                                base_psi,
                                                base_lambda)
        print(f"  PyTorch Eager: {pytorch_eager_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'PyTorch Eager', 'time_ms': pytorch_eager_time
        })

        # PyTorch Compiled Baseline Benchmarking
        scores_copy_compiled = scores_orig.clone() # Clone for this specific run
        pytorch_compiled_time = time_cuda_function(run_pytorch_compiled,
                                                   scores_copy_compiled,
                                                   bus_tensor,
                                                   history_indices,
                                                   d,
                                                   base_psi,
                                                   base_lambda)
        print(f"  PyTorch Compiled: {pytorch_compiled_time:.4f} ms")
        benchmark_results.append({
            'n': n, 'depth': d, 'implementation': 'PyTorch Compiled', 'time_ms': pytorch_compiled_time
        })

# 4. Print the collected benchmarking results in a clear format
results_df = pd.DataFrame(benchmark_results)
print("\nBenchmarking Results:")
print(results_df.to_string())

"""## Benchmark Depth-Minimized Regime

### Subtask:
Run benchmarks for the PSI kernel, PyTorch eager baseline, and PyTorch compiled baseline specifically for `depth = 1`, using both randomly generated indices and contiguous indices.

**Reasoning**:
I will initialize an empty list to store the benchmark results for the depth-minimized regime. Then, I will iterate through the specified 'n' values, and for each 'n', I will generate inputs, prepare both random and contiguous history indices, and benchmark the custom kernel, PyTorch eager, and PyTorch compiled implementations. Finally, I will store and print the results in a Pandas DataFrame.
"""

import pandas as pd
import random
import torch

# 1. Initialize an empty list to store benchmarking results for this regime
depth_1_benchmark_results = []

# 2. Define a fixed depth = 1 for this regime
fixed_depth = 1

# 3. Define a list of n values
n_values_depth_1 = [64, 128, 256, 512, 1024]

max_bus_fragments = 1000000 # As hardcoded in the custom kernel

print("Starting benchmarking for Depth-Minimized Regime (depth=1)...")

# 4. Iterate through each n value
for n in n_values_depth_1:
    print(f"\nBenchmarking for n={n}, depth={fixed_depth}")

    # a. Generate random inputs (scores, bus_tensor, base_psi, base_lambda)
    # history_indices generated here will be used as 'Random Indices'
    scores_orig, bus_tensor, history_indices_random, _, base_psi, base_lambda = \
        generate_random_inputs(n, fixed_depth, max_bus_fragments, device='cuda')

    # b. Create two sets of history_indices for the current n and depth = 1

    # i. Random Indices (already generated above as history_indices_random)

    # ii. Contiguous Indices
    # All indices are valid and contiguous (0 to n-1)
    history_indices_contiguous = torch.arange(0, n, dtype=torch.int32, device='cuda').unsqueeze(0)
    # Ensure the history_indices tensor has the correct number of rows for the depth
    # In this case, depth=1, so it should be (1, n)

    # Store index types and corresponding history_indices tensors in a dict
    index_types = {
        'random': history_indices_random,
        'contiguous': history_indices_contiguous
    }

    for index_type_name, current_history_indices in index_types.items():
        print(f"  Using {index_type_name} indices:")

        # Prepare wrapper functions for benchmarking
        def run_custom_kernel(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
            return ext.launch_psilong(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

        def run_pytorch_eager(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_baseline_op(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

        def run_pytorch_compiled(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
            return pytorch_compiled_op(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

        # iii. & iv. Run and measure for each implementation

        # Custom Kernel Benchmarking
        scores_copy_custom = scores_orig.clone() # Clone for this specific run
        custom_kernel_time = time_cuda_function(run_custom_kernel,
                                                scores_copy_custom,
                                                bus_tensor,
                                                current_history_indices,
                                                fixed_depth,
                                                base_psi,
                                                base_lambda)
        print(f"    Custom Kernel: {custom_kernel_time:.4f} ms")
        depth_1_benchmark_results.append({
            'n': n, 'depth': fixed_depth, 'implementation': 'Custom Kernel',
            'index_type': index_type_name, 'time_ms': custom_kernel_time
        })

        # PyTorch Eager Baseline Benchmarking
        scores_copy_eager = scores_orig.clone() # Clone for this specific run
        pytorch_eager_time = time_cuda_function(run_pytorch_eager,
                                                scores_copy_eager,
                                                bus_tensor,
                                                current_history_indices,
                                                fixed_depth,
                                                base_psi,
                                                base_lambda)
        print(f"    PyTorch Eager: {pytorch_eager_time:.4f} ms")
        depth_1_benchmark_results.append({
            'n': n, 'depth': fixed_depth, 'implementation': 'PyTorch Eager',
            'index_type': index_type_name, 'time_ms': pytorch_eager_time
        })

        # PyTorch Compiled Baseline Benchmarking
        scores_copy_compiled = scores_orig.clone() # Clone for this specific run
        pytorch_compiled_time = time_cuda_function(run_pytorch_compiled,
                                                   scores_copy_compiled,
                                                   bus_tensor,
                                                   current_history_indices,
                                                   fixed_depth,
                                                   base_psi,
                                                   base_lambda)
        print(f"    PyTorch Compiled: {pytorch_compiled_time:.4f} ms")
        depth_1_benchmark_results.append({
            'n': n, 'depth': fixed_depth, 'implementation': 'PyTorch Compiled',
            'index_type': index_type_name, 'time_ms': pytorch_compiled_time
        })

# 5. Convert the collected benchmarking results into a Pandas DataFrame and print it.
results_df_depth_1 = pd.DataFrame(depth_1_benchmark_results)
print("\nBenchmarking Results for Depth-Minimized Regime (depth=1):")
print(results_df_depth_1.to_string())

"""## Benchmark Memory-Coalesced Regime

### Subtask:
Run benchmarks for the PSI kernel, PyTorch eager baseline, and PyTorch compiled baseline ensuring `history_indices` are contiguous/sorted for optimal memory access patterns.

**Reasoning**:
I will initialize an empty list for the benchmarking results, define the `n` values and a fixed depth, then iterate through each `n` value. Inside the loop, I will generate random inputs, create contiguous `history_indices`, and benchmark the custom kernel, PyTorch eager, and PyTorch compiled implementations, storing the results in the list. Finally, I will convert the results into a Pandas DataFrame and print it.
"""

import pandas as pd
import random
import torch

# 1. Initialize an empty list to store benchmarking results for this regime
memory_coalesced_benchmark_results = []

# 2. Define lists for n values and a fixed depth for this regime
n_values_coalesced = [64, 128, 256, 512, 1024]
fixed_depth_coalesced = 5

max_bus_fragments = 1000000 # As hardcoded in the custom kernel

print(f"Starting benchmarking for Memory-Coalesced Regime (depth={fixed_depth_coalesced})...")

# 3. Iterate through each n value
for n in n_values_coalesced:
    print(f"\nBenchmarking for n={n}, depth={fixed_depth_coalesced}")

    # a. Generate initial random inputs (scores, bus_tensor, base_psi, base_lambda)
    scores_orig, bus_tensor, _, _, base_psi, base_lambda = \
        generate_random_inputs(n, fixed_depth_coalesced, max_bus_fragments, device='cuda')

    # b. Create history_indices for contiguous memory access
    # Each history_indices[d, idx] is simply idx
    # The actual bus_memory access will be bus_memory[frag_idx], so if frag_idx is sequential,
    # it encourages coalesced memory access within the bus_memory tensor itself.
    history_indices_contiguous = torch.arange(0, n, dtype=torch.int32, device='cuda').unsqueeze(0).repeat(fixed_depth_coalesced, 1)

    print(f"  Using contiguous indices for depth={fixed_depth_coalesced}:")

    # c. Define wrapper functions for benchmarking
    def run_custom_kernel(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
        return ext.launch_psilong(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

    def run_pytorch_eager(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
        return pytorch_baseline_op(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

    def run_pytorch_compiled(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda):
        return pytorch_compiled_op(scores_copy_inner, bus_t, hist_idx, dep, b_psi, b_lambda)

    # d. Run and measure for each implementation

    # Custom Kernel Benchmarking
    scores_copy_custom = scores_orig.clone() # Clone for this specific run
    custom_kernel_time = time_cuda_function(run_custom_kernel,
                                            scores_copy_custom,
                                            bus_tensor,
                                            history_indices_contiguous,
                                            fixed_depth_coalesced,
                                            base_psi,
                                            base_lambda)
    print(f"    Custom Kernel: {custom_kernel_time:.4f} ms")
    memory_coalesced_benchmark_results.append({
        'n': n, 'depth': fixed_depth_coalesced, 'implementation': 'Custom Kernel',
        'index_type': 'contiguous', 'time_ms': custom_kernel_time
    })

    # PyTorch Eager Baseline Benchmarking
    scores_copy_eager = scores_orig.clone() # Clone for this specific run
    pytorch_eager_time = time_cuda_function(run_pytorch_eager,
                                            scores_copy_eager,
                                            bus_tensor,
                                            history_indices_contiguous,
                                            fixed_depth_coalesced,
                                            base_psi,
                                            base_lambda)
    print(f"    PyTorch Eager: {pytorch_eager_time:.4f} ms")
    memory_coalesced_benchmark_results.append({
        'n': n, 'depth': fixed_depth_coalesced, 'implementation': 'PyTorch Eager',
        'index_type': 'contiguous', 'time_ms': pytorch_eager_time
    })

    # PyTorch Compiled Baseline Benchmarking
    scores_copy_compiled = scores_orig.clone() # Clone for this specific run
    pytorch_compiled_time = time_cuda_function(run_pytorch_compiled,
                                               scores_copy_compiled,
                                               bus_tensor,
                                               history_indices_contiguous,
                                               fixed_depth_coalesced,
                                               base_psi,
                                               base_lambda)
    print(f"    PyTorch Compiled: {pytorch_compiled_time:.4f} ms")
    memory_coalesced_benchmark_results.append({
        'n': n, 'depth': fixed_depth_coalesced, 'implementation': 'PyTorch Compiled',
        'index_type': 'contiguous', 'time_ms': pytorch_compiled_time
    })

# 4. Convert the collected benchmarking results into a Pandas DataFrame and print it.
results_df_memory_coalesced = pd.DataFrame(memory_coalesced_benchmark_results)
print("\nBenchmarking Results for Memory-Coalesced Regime:")
print(results_df_memory_coalesced.to_string())

"""## Benchmark Batch Amortization Regime

### Subtask:
Run benchmarks where the operation is executed `B` times back-to-back before synchronization, for `B ∈ {1, 8, 32, 128}`, comparing the PSI kernel, PyTorch eager baseline, and PyTorch compiled baseline.

**Reasoning**:
I will initialize an empty list for batch amortization benchmarking results, define the n, depth, and B values, and then iterate through these combinations. For each combination, I will generate inputs, create batched wrapper functions, and benchmark the custom kernel, PyTorch eager, and PyTorch compiled implementations using the `time_cuda_function`. Finally, I will store the results in a DataFrame and print it.
"""

import pandas as pd
import random
import torch

# 1. Initialize an empty list to store benchmarking results for this regime
batch_amortization_benchmark_results = []

# 2. Define lists for n, depth, and B values
n_values_amortization = [64, 256, 1024]
depth_values_amortization = [1, 5]
B_values = [1, 8, 32, 128] # Batch sizes

max_bus_fragments = 1000000 # As hardcoded in the custom kernel

print("Starting benchmarking for Batch Amortization Regime...")

# 3. Iterate through each n value, then each depth value, and finally each B value.
for n in n_values_amortization:
    for d in depth_values_amortization:
        # Generate initial random inputs for n and d once per (n, d) combination
        scores_orig, bus_tensor, history_indices, current_depth, base_psi, base_lambda = \
            generate_random_inputs(n, d, max_bus_fragments, device='cuda')

        for B in B_values:
            print(f"\nBenchmarking for n={n}, depth={d}, B={B}")

            # b. Define wrapper functions for benchmarking B times back-to-back
            # Each wrapper needs to accept a list of scores_copies (one for each batch element b)

            # Wrapper for Custom Kernel (Batched)
            def run_custom_kernel_batched(scores_copies_list, bus_t, hist_idx, dep, b_psi, b_lambda):
                for b in range(B):
                    ext.launch_psilong(scores_copies_list[b], bus_t, hist_idx, dep, b_psi, b_lambda)

            # Wrapper for PyTorch Eager Baseline (Batched)
            def run_pytorch_eager_batched(scores_copies_list, bus_t, hist_idx, dep, b_psi, b_lambda):
                for b in range(B):
                    pytorch_baseline_op(scores_copies_list[b], bus_t, hist_idx, dep, b_psi, b_lambda)

            # Wrapper for PyTorch Compiled Baseline (Batched)
            def run_pytorch_compiled_batched(scores_copies_list, bus_t, hist_idx, dep, b_psi, b_lambda):
                for b in range(B):
                    pytorch_compiled_op(scores_copies_list[b], bus_t, hist_idx, dep, b_psi, b_lambda)

            # c. Create a list of B cloned scores_orig tensors for each implementation
            scores_copies_custom = [scores_orig.clone() for _ in range(B)]
            scores_copies_eager = [scores_orig.clone() for _ in range(B)]
            scores_copies_compiled = [scores_orig.clone() for _ in range(B)]

            # d. Call time_cuda_function for each of the batch-amortized wrapper functions

            # Custom Kernel Benchmarking
            custom_kernel_time_batched = time_cuda_function(run_custom_kernel_batched,
                                                            scores_copies_custom,
                                                            bus_tensor,
                                                            history_indices,
                                                            d,
                                                            base_psi,
                                                            base_lambda)
            print(f"  Custom Kernel (B={B}): {custom_kernel_time_batched:.4f} ms")
            batch_amortization_benchmark_results.append({
                'n': n, 'depth': d, 'B': B, 'implementation': 'Custom Kernel', 'time_ms': custom_kernel_time_batched
            })

            # PyTorch Eager Baseline Benchmarking
            pytorch_eager_time_batched = time_cuda_function(run_pytorch_eager_batched,
                                                            scores_copies_eager,
                                                            bus_tensor,
                                                            history_indices,
                                                            d,
                                                            base_psi,
                                                            base_lambda)
            print(f"  PyTorch Eager (B={B}): {pytorch_eager_time_batched:.4f} ms")
            batch_amortization_benchmark_results.append({
                'n': n, 'depth': d, 'B': B, 'implementation': 'PyTorch Eager', 'time_ms': pytorch_eager_time_batched
            })

            # PyTorch Compiled Baseline Benchmarking
            pytorch_compiled_time_batched = time_cuda_function(run_pytorch_compiled_batched,
                                                               scores_copies_compiled,
                                                               bus_tensor,
                                                               history_indices,
                                                               d,
                                                               base_psi,
                                                               base_lambda)
            print(f"  PyTorch Compiled (B={B}): {pytorch_compiled_time_batched:.4f} ms")
            batch_amortization_benchmark_results.append({
                'n': n, 'depth': d, 'B': B, 'implementation': 'PyTorch Compiled', 'time_ms': pytorch_compiled_time_batched
            })

# 5. Convert the collected benchmarking results into a Pandas DataFrame and print it.
results_df_batch_amortization = pd.DataFrame(batch_amortization_benchmark_results)
print("\nBenchmarking Results for Batch Amortization Regime:")
print(results_df_batch_amortization.to_string())

"""## Analyze Results and Conclude

### Subtask:
Collect and analyze all benchmarking data from the different regimes. Identify any scenarios, configurations, or implementation details where the PyTorch baseline (eager or compiled) demonstrably outperforms the PSI CUDA kernel. Finally, provide a clear conclusion stating whether the claim was successfully falsified, detailing the specific conditions under which PyTorch was faster, or explaining why falsification was not achieved despite trying all mandatory tactics. Summarize the findings, including the performance comparison across all tested regimes and the final verdict on the claim.

**Reasoning**:
I will consolidate all benchmarking results into a single DataFrame, then calculate performance ratios to compare the Custom Kernel against PyTorch Eager and PyTorch Compiled baselines across all scenarios. This will involve handling missing columns and then pivoting the data for easier comparison.
"""

import pandas as pd

# Prepare results_df (Small-n Regime) - implicitly random indices, B=1
small_n_df = results_df.copy()
small_n_df['index_type'] = 'random'
small_n_df['B'] = 1

# Prepare results_df_depth_1 (Depth-Minimized Regime) - B=1
depth_1_df = results_df_depth_1.copy()
depth_1_df['B'] = 1

# Prepare results_df_memory_coalesced (Memory-Coalesced Regime) - B=1
memory_coalesced_df = results_df_memory_coalesced.copy()
memory_coalesced_df['B'] = 1

# Prepare results_df_batch_amortization (Batch Amortization Regime) - implicitly random indices
batch_amortization_df = results_df_batch_amortization.copy()
batch_amortization_df['index_type'] = 'random'

# Combine all dataframes
combined_df = pd.concat([
    small_n_df,
    depth_1_df,
    memory_coalesced_df,
    batch_amortization_df
], ignore_index=True)

# Fill any NaN values that might arise from different column sets (e.g., index_type or B for some entries)
combined_df['index_type'] = combined_df['index_type'].fillna('N/A')
combined_df['B'] = combined_df['B'].fillna(1).astype(int)

# Pivot the table to easily compare implementations
pivoted_df = combined_df.pivot_table(
    index=['n', 'depth', 'index_type', 'B'],
    columns='implementation',
    values='time_ms'
).reset_index()

# Calculate performance ratios relative to Custom Kernel
pivoted_df['PyTorch Eager vs Custom Kernel'] = pivoted_df['Custom Kernel'] / pivoted_df['PyTorch Eager']
pivoted_df['PyTorch Compiled vs Custom Kernel'] = pivoted_df['Custom Kernel'] / pivoted_df['PyTorch Compiled']

# Calculate speedup factors (how many times faster Custom Kernel is)
pivoted_df['Custom Kernel Speedup vs Eager'] = pivoted_df['PyTorch Eager'] / pivoted_df['Custom Kernel']
pivoted_df['Custom Kernel Speedup vs Compiled'] = pivoted_df['PyTorch Compiled'] / pivoted_df['Custom Kernel']

print("Combined and pivoted benchmarking results:")
print(pivoted_df.to_string())

"""### Analysis of Benchmarking Results

The `pivoted_df` provides a comprehensive view of the performance of the Custom CUDA Kernel, PyTorch Eager baseline, and PyTorch Compiled baseline across various configurations of `n` (number of elements), `depth`, `index_type` (random or contiguous), and `B` (batch size for amortization).

Let's analyze the `Custom Kernel Speedup vs Eager` and `Custom Kernel Speedup vs Compiled` columns. A value greater than 1 indicates that the Custom Kernel is faster, and the value represents how many times faster it is. Conversely, a value less than 1 would indicate that the PyTorch baseline is faster.

Looking at the `pivoted_df`:

**Overall Performance Comparison:**
Across all tested regimes (Small-n, Depth-Minimized, Memory-Coalesced, and Batch Amortization), the **Custom CUDA Kernel consistently and significantly outperforms both the PyTorch Eager and PyTorch Compiled baselines.**

- The custom kernel is often **100x to 600x faster** than the PyTorch Eager baseline.
- The custom kernel is often **100x to 600x faster** than the PyTorch Compiled baseline.

**Specific Scenarios where PyTorch Outperformed the Custom Kernel:**
Based on the `Custom Kernel Speedup vs Eager` and `Custom Kernel Speedup vs Compiled` columns, there are **no scenarios** where PyTorch Eager or PyTorch Compiled demonstrably outperforms the Custom Kernel. All values in these columns are significantly greater than 1, indicating that the Custom Kernel was always faster.

**Magnitude of Performance Differences:**

- **Small-n Regime (n=64-1024, depth=1-5, random indices, B=1):** The custom kernel is generally 70x to 330x faster than PyTorch Eager and 80x to 330x faster than PyTorch Compiled. For `n=64, depth=5`, the custom kernel is around 300x faster.
- **Depth-Minimized Regime (depth=1, random/contiguous indices, B=1):**
    - With **random indices**, the custom kernel is 70x to 130x faster than Eager and 80x to 140x faster than Compiled.
    - With **contiguous indices**, the custom kernel performs even better, being 100x to 130x faster than Eager and 100x to 130x faster than Compiled. This highlights the memory access benefits for the custom kernel.
- **Memory-Coalesced Regime (depth=5, contiguous indices, B=1):** The custom kernel maintains its strong lead, being about 200x to 330x faster than Eager and 200x to 330x faster than Compiled.
- **Batch Amortization Regime (various n, depth, B=1, 8, 32, 128, random indices):** As `B` increases, the absolute times for all implementations increase, but the relative speedup of the custom kernel generally improves or stays high.
    - For `B=1`, the custom kernel is 70x to 300x faster.
    - For `B=128`, the speedup can reach up to ~550x against Eager and ~600x against Compiled.

### Conclusion

The claim, "_PyTorch can outperform the custom kernel in any scenario_", was **not successfully falsified** based on the conducted benchmarks. In fact, the benchmarks overwhelmingly demonstrate the opposite: the Custom CUDA Kernel consistently and significantly outperforms both the PyTorch Eager and PyTorch Compiled baselines across all tested conditions, including:

- Small 'n' values
- Minimized depth (depth=1)
- Memory-coalesced access patterns (contiguous indices)
- Batch amortization

In every single scenario measured, the Custom Kernel was faster, often by two to three orders of magnitude (100x to 600x). This strong performance advantage of the custom kernel indicates that for this specific operation, writing a specialized CUDA kernel is indeed highly beneficial compared to relying on PyTorch's native or compiled tensor operations, especially given the fine-grained memory access and loop structure of the problem.

## Final Task

### Subtask:
Summarize the findings, including the performance comparison across all tested regimes and the final verdict on the claim.

## Summary:

### Q&A
No, PyTorch (eager or compiled) did not outperform the custom CUDA kernel in any of the tested scenarios. The custom kernel consistently demonstrated superior performance across all regimes, often by several orders of magnitude.

### Data Analysis Key Findings

*   The custom CUDA kernel from `/content/final_kernel.cu` was successfully compiled and loaded as a PyTorch C++ extension after resolving initial compilation and linking issues related to missing PyTorch and Python include paths.
*   A PyTorch-native baseline implementation (`pytorch_baseline_op`) was successfully developed, accurately replicating the complex logic of the custom kernel, including numerical stability measures and value clamping.
*   The numerical correctness of the `pytorch_baseline_op` was thoroughly verified against the custom CUDA kernel, with outputs matching within stringent tolerances of `max_abs_error <= 1e-5` and `max_rel_error <= 1e-5` across various random inputs.
*   **Overall Performance Comparison:** Across all tested regimes (small 'n', minimized depth, memory-coalesced access, and batch amortization), the custom CUDA kernel consistently and significantly outperformed both PyTorch eager and PyTorch compiled baselines.
    *   The custom kernel was often **100x to 600x faster** than the PyTorch eager baseline.
    *   The custom kernel was often **100x to 600x faster** than the PyTorch compiled baseline.
*   **Small-n Regime:** For `n` values ranging from 64 to 1024 and depths from 1 to 5, the custom kernel was 70x to 330x faster than PyTorch baselines.
*   **Depth-Minimized Regime (`depth=1`):** The custom kernel maintained a substantial lead, being 70x to 140x faster than PyTorch baselines, with slightly better relative performance for contiguous indices.
*   **Memory-Coalesced Regime:** With optimal memory access patterns, the custom kernel's advantage was pronounced, performing 200x to 330x faster than PyTorch baselines.
*   **Batch Amortization Regime:** As the batch size `B` increased from 1 to 128, the custom kernel's relative speedup often increased, reaching up to 550x against eager and 600x against compiled PyTorch for `B=128`.
*   **Final Verdict on the Claim:** The claim that "PyTorch can outperform the custom kernel in any scenario" was **not falsified**. The custom CUDA kernel was found to be superior in every single tested condition, providing no evidence of PyTorch outperforming it.

### Insights or Next Steps
*   For performance-critical operations involving complex loop structures, conditional logic, and specific memory access patterns like those in the custom kernel, specialized CUDA implementations offer significant performance advantages (100-600x faster) over generic PyTorch eager or compiled equivalents.
*   Future optimizations for the PyTorch baseline could explore alternative tensor operations or specialized PyTorch features (if available for such a complex pattern) to narrow the performance gap, although matching a highly optimized custom kernel might be challenging.
"""